### PR TITLE
Implement CarbonBlack ping transmission module

### PR DESCRIPTION
**Pull request by Collin-Richards**
I've implemented the ping transmission module. The other transmission modules components are not yet implemented. I'm not sure if you'd rather have smaller PR's for each component or one larger one with all of them implemented. We can discuss that below.

### CODE REVIEW

**Comment by Collin-Richards** [comment]
Also as a side note, I noticed that the travis build is running some linting code, but it doesn't appear to actually care if the linting passes. Is that intentional?

**Comment by delliott90** [comment]
It would be better to have the entire module with both translation and transmission filled out before submitting a PR. Regarding the linting code, it may be that something needs fixed on travis.

**Comment by Collin-Richards** [comment]
Ok. I'll keep working on this branch and submit a new request when both translation and transmission are implemented.

**Comment by delliott90** [comment]
Take a look at this PR, https://github.com/IBM/stix-shifter/pull/96, I simplified the transmission modules a bit for the Dummy and QRadar modules. I put all of the methods in the connector class rather than having separate classes for each method.

**Pull request closed without merging**
